name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend/

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - run: npm ci

    - name: Set up .env file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: Persist uploads directory
      uses: actions/upload-artifact@v2
      with:
        name: backend-uploads
        path: ./backend/uploads

    - run: cp -r uploads/* /home/atozer/Desktop/uploads/
    - run: cp -r /home/atozer/Desktop/uploads/* uploads/

    - name: Run server
      run: pm2 restart virtual-campus-api
