name: Node.js CI/CD

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  build:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend/

    steps:
    - uses: actions/checkout@v4

    - name: Set up .env file
      run: |
        touch .env
        echo ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" > .env
        echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> .env
        echo NODE_ENV="${{ secrets.NODE_ENV }}" >> .env
        echo PORT="${{ secrets.PORT }}" >> .env

    # Build and start services using Docker Compose
    - name: Build and start Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
